apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-client-secret
  namespace: prognose
type: Opaque
data:
  # Base64 encoded webhook secret - replace with your actual secret
  # To encode: echo -n "your-webhook-secret" | base64
  # Base64 encoded value of the secret proposed in the web-app
  WEBHOOK_SECRET: <b64-secret-value>
